### ISSUE TITLE
Incompatibility with Log4j-2.6.2

### ISSUE THREAD

**Issue by barsen** [jurmous/logstash-log4j2#18]
@jurmous 
Are there any plans to maintain this plugin? It's awesome but a bit outdated.

`{:timestamp=>"2016-08-19T18:17:50.431000+0000", :message=>"Accepted connection", :client=>"172.172.50.4:58479", :server=>"0.0.0.0:7000", :level=>:debug, :file=>"logstash/inputs/log4j2.rb", :line=>"151", :method=>"run"}
{:timestamp=>"2016-08-19T18:17:50.539000+0000", :level=>:debug, :message=>"org.apache.logging.log4j.core.impl.Log4jLogEvent$LogEventProxy; local class incompatible: stream classdesc serialVersionUID = -8634075037355293699, local class serialVersionUID = -7139032940312647146", :exception=>IOError, :backtrace=>["org/jruby/ext/jruby/JRubyObjectInputStream.java:58:in`read_object'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-log4j2-logstash2-5.2.1-java/lib/logstash/inputs/log4j2.rb:85:in `handle_socket'", "org/jruby/RubyKernel.java:1479:in`loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-log4j2-logstash2-5.2.1-java/lib/logstash/inputs/log4j2.rb:83:in `handle_socket'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-log4j2-logstash2-5.2.1-java/lib/logstash/inputs/log4j2.rb:152:in`run'"], :file=>"logstash/inputs/log4j2.rb", :line=>"115", :method=>"handle_socket"}
`

**Comment by afrimberger** [comment]
I've updated the plugin to support log4j2 2.6.2. You can use my release till the corresponding pull request gets merged:
https://github.com/afrimberger/logstash-log4j2/releases/tag/release-6.2.1
